name: CI to build kube-cross image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  path-context:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-kube-cross
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/kube-cross:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/kube-cross:v1.15.1
          build-args: |
            ETCD_VERSION=v3.4.13
            GO_VERSION=1.15.5
            PROTOBUF_VERSION=3.7.0
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

